spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KCaiJ/tensquare-config.git
  rabbitmq:
    host: 192.168.0.128
server:
  port: 12000

management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh